//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FASIDSEntities : DbContext
    {
        public FASIDSEntities()
            : base("name=FASIDSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NewPolygonGeoJson> NewPolygonGeoJsons { get; set; }
        public DbSet<PolygonGeoJson> PolygonGeoJsons { get; set; }
        public DbSet<PostAnswer> PostAnswers { get; set; }
        public DbSet<PostQuestion> PostQuestions { get; set; }
        public DbSet<Product_list> Product_list { get; set; }
        public DbSet<ProductData> ProductDatas { get; set; }
        public DbSet<ProductList_new> ProductList_new { get; set; }
        public DbSet<TreatmentSiteCode> TreatmentSiteCodes { get; set; }
        public DbSet<UserData> UserDatas { get; set; }
        public DbSet<UserImage> UserImages { get; set; }
    }
}
