//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostAnswer
    {
        public string UserId { get; set; }
        public int QuestionId { get; set; }
        public int AnswerId { get; set; }
        public string AnswerContent { get; set; }
        public string AnswerAuthor { get; set; }
        public System.DateTime AnswerPostDate { get; set; }
    
        public virtual PostQuestion PostQuestion { get; set; }
        public virtual UserData UserData { get; set; }
    }
}
