//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductList_new
    {
        public int ProductId { get; set; }
        public string ActiveIngredient { get; set; }
        public string ProductName { get; set; }
        public string Manufacturer_ { get; set; }
        public string PesticideClassification { get; set; }
        public string PhysicalForm { get; set; }
        public string IsSynthetic_ { get; set; }
        public string ControlMethod { get; set; }
        public string TreatmentMethod { get; set; }
        public Nullable<double> Broadcast_MinUseRate { get; set; }
        public Nullable<double> Broadcast_MaxUseRate { get; set; }
        public string Broadcast_MeasurementUnit { get; set; }
        public Nullable<double> Mound_MinUseRate { get; set; }
        public Nullable<double> Mound_MaxUseRate { get; set; }
        public string Mound_MeasurementUnit { get; set; }
        public string LandType { get; set; }
        public string UrbanBroadcastSites { get; set; }
        public string UrbanMoundSites { get; set; }
        public string AgriBroadcastSites { get; set; }
        public string AgriMoundSites { get; set; }
        public string AgriFoodProducingType { get; set; }
        public string AgriFoodProducingSites { get; set; }
        public string AgriNonFoodProducingSites { get; set; }
        public string MaunfacturerUrl { get; set; }
        public string Note { get; set; }
    }
}
