//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_list
    {
        public string ActiveIngredient { get; set; }
        public string ProductName { get; set; }
        public string Manufacturer_ { get; set; }
        public string PesticideClassification { get; set; }
        public string PhysicalForm { get; set; }
        public bool IsSynthetic_ { get; set; }
        public string ControlMethod { get; set; }
        public bool IsBroadcast { get; set; }
        public bool IsMound { get; set; }
        public Nullable<double> Broadcast_MinUseRate { get; set; }
        public Nullable<double> Broadcast_MaxUseRate { get; set; }
        public string Broadcast_MeasurementUnit { get; set; }
        public Nullable<double> Mound_MinUseRate { get; set; }
        public Nullable<double> Mound_MaxUseRate { get; set; }
        public string Mound_MeasurementUnit { get; set; }
        public bool IsUrbanLand { get; set; }
        public bool IsUrbanHome_Broadcast { get; set; }
        public bool IsUrbanHome_Mound { get; set; }
        public bool IsUrbanPerimeter_P { get; set; }
        public bool IsUrbanRecArea_Broadcast { get; set; }
        public bool IsUrbanRecArea_Mound { get; set; }
        public bool IsUrbanRightOfWay_Broadcast { get; set; }
        public bool IsUrbanRightOfWay_Mound { get; set; }
        public bool IsAgricultureLand { get; set; }
        public bool IsAgriPasture_Broadcast { get; set; }
        public bool IsAgriPasture_Mound { get; set; }
        public bool IsAgriPoultry_Broadcast { get; set; }
        public bool IsAgriPoultry_Mound { get; set; }
        public bool IsAgriCropAreas_Broadcast { get; set; }
        public bool IsAgriCropAreas_Mound { get; set; }
        public bool IsAgriOthers_Broadcast { get; set; }
        public bool IsAgriOthers_Mound { get; set; }
        public bool IsAgriSod_Broadcast { get; set; }
        public bool IsAgriSod_Mound { get; set; }
        public bool IsAgriNurseryContainer_Broadcast { get; set; }
        public bool IsAgriNurseryContainer_Mound { get; set; }
        public bool IsAgriNurseryBB_Broadcast { get; set; }
        public bool IsAgriNurseryBB_Mound { get; set; }
        public bool IsAgri_FoodProducing { get; set; }
        public bool IsAgri_NonFoodProducing { get; set; }
        public string AgriFoodProducingSites { get; set; }
        public string AgriNonFoodProducingSites { get; set; }
        public string MaunfacturerUrl { get; set; }
        public string Note { get; set; }
        public int ProductId { get; set; }
    }
}
