//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentSiteCode
    {
        public string Code { get; set; }
        public string SiteType { get; set; }
        public string TreatmentType { get; set; }
        public int CodeId { get; set; }
    }
}
