//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImage
    {
        public string UserId { get; set; }
        public string ImageId { get; set; }
        public string ImagePath { get; set; }
    
        public virtual UserData UserData { get; set; }
    }
}
