//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImage
    {
        public int UserId { get; set; }
        public int ImageId { get; set; }
        public int IamgeSize { get; set; }
        public string ImageFileName { get; set; }
        public byte[] ImageData { get; set; }
    
        public virtual UserData UserData { get; set; }
    }
}
