//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.Spatial;
    
    public partial class PolygonGeoJson2
    {
        public int UserId { get; set; }
        public string Type { get; set; }
        public string GeometryType { get; set; }
        public string PolygonName { get; set; }
        public string Address { get; set; }
        public string Notes { get; set; }
        public Nullable<double> TotalArea { get; set; }
        public Nullable<double> MoundDensity { get; set; }
        public Nullable<int> MoundNumber { get; set; }
        public string EnvMapTypeId { get; set; }
        public int EnvMapTilt { get; set; }
        public Nullable<double> Bounds_SW_Lat { get; set; }
        public Nullable<double> Bounds_SW_Lng { get; set; }
        public Nullable<double> Bounds_NE_Lat { get; set; }
        public Nullable<double> Bounds_NE_Lng { get; set; }
        public string GeoJsonId { get; set; }
        public System.Data.Spatial.DbGeometry Coordinates { get; set; }
        public string TypeOfLand { get; set; }
        public string TypeOfUrban { get; set; }
        public string TypeOfAgri { get; set; }
        public string TypeOfControlMethod { get; set; }
        public string TypeOfTreatment { get; set; }
    
        public virtual UserData UserData { get; set; }
    }
}
